name: dependencias
description: A new Flutter package project.
version: 0.0.1
homepage: none

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Flutter Team
  logger: ^1.1.0
  http: ^0.13.4
  url_launcher: ^6.0.17
  camera: ^0.9.4+5
  shared_preferences: ^2.0.10
  google_maps_flutter: ^2.1.1
  image_picker: ^0.8.4+4
  intl: ^0.17.0
  package_info: ^2.0.2
  connectivity: ^3.0.6
  device_info: ^2.0.3
  path_provider: ^2.0.8
  flutter_datetime_picker: ^1.5.1
  super_tooltip: ^1.0.1

  # Firebase
  firebase_core: ^1.10.5
  firebase_crashlytics: ^2.4.3
  firebase_messaging: ^11.2.3
  firebase_analytics: ^9.0.3
  dio_firebase_performance: ^0.3.1-dev.3

  # Another Team
  flutter_bloc: ^8.0.0
  google_fonts: 2.1.0
  carousel_slider: ^4.0.0
  dotted_border: ^2.0.0+1
  geolocator: ^7.7.1
  geocoding: ^2.0.1
  cached_network_image: ^3.2.0
  badges: ^2.0.2
  equatable: ^2.0.3
  clevertap_plugin: ^1.4.0
  flutter_html: ^2.0.0-nullsafety.0
  flutter_svg: ^0.22.0
  shimmer: ^2.0.0
  screenshot: ^1.2.3
  image_gallery_saver: ^1.7.1
  flutter_branch_sdk: ^3.5.0
  uni_links: ^0.5.1
  flutter_google_places: ^0.3.0
  mask_text_input_formatter: ^2.0.0
  painter: ^2.0.0
  time_range_picker: ^2.1.0
  flutter_modular: ^4.5.0
  native_screenshot: ^1.0.0
  dart_ipify: ^1.1.1
  modular_interfaces: 1.0.4
  collection: ^1.15.0
  native_updater: ^0.1.0
  in_app_review: ^2.0.3
  multiple_localization: ^0.2.2
  algolia: ^1.0.4
  barcode_widget: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  bloc_test: ^9.0.1
  mocktail: ^0.2.0
  build_runner: ^2.1.5
  modular_test: ^1.0.1+1
  flutter_launcher_icons: "^0.9.2"

flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
